### ISSUE TITLE
idea: add a `reload` message that forces clients to reload the page following a deployment

### ISSUE THREAD

**Issue by username-is-required** [reddark-remix/reddark-remix#12]
something i noticed on my own fork was that, if i updated the front-end code, the changes would inevitably be very slow to propagate to clients. this is because - after a redeployment - most users do not seem to refresh the page (and are therefore left with an old version of the front-end that establishes a connection to the updated back-end process).

to solve this, i introduced a `reload` message, which - providing an environment variable is set to `true` - is emitted from the server after the first check (following a deployment) has been completed. i also modified the front-end javascript to listen for the `reload` message, and to reload the page anywhere between 0-20s after receipt (staggered to prevent the server being spammed with every client reloading at once).

i’ve copied the [frontend js code](https://github.com/username-is-required/reddark/blob/ed6a3d7ed8a8081462aa54f3d8ee4de7f7a8ce2e/public/index.js#L75-L81) i used to implement this below. i’ve also included a link to my backend implementation (written in node.js).

```js
socket.on("reload", () => {
    // reload the page in between 0-20s
    // (staggered to hopefully not kill my server by way of an accidental ddos)
    setTimeout(() => {
        location.reload();
    }, Math.floor(Math.random() * 20000));
});
```

[link to backend code](https://github.com/username-is-required/reddark/blob/ed6a3d7ed8a8081462aa54f3d8ee4de7f7a8ce2e/main.js#L272-L278)

**Comment by username-is-required** [comment]
the only problem i’ve noticed is that reloading the page resets the client’s audio alert preferences. however that should be a fairly simple fix (if needed), maybe with a cookie, with audio preferences stored after a `#` in the url, etc.

**Comment by rewbycraft** [comment]
I've added the reload command itself. But I need to find someone else willing to figure out the preservation of settings.

**Comment by rewbycraft** [comment]
Implemented.
