### ISSUE TITLE
List of subs to go dark

### ISSUE THREAD

**Issue by abrahami** [reddark-remix/reddark-remix#21]
hi,
thanks for this amazing effort!
Is it possible to get a list of all subreddits that go dark (regardless of time/duration) - only if they joined the protest?

thanks!

**Comment by Anonymous941** [comment]
Do you mean to exclude ones that have gone dark for other reasons?  I doubt that's very many

**Comment by abrahami** [comment]
No, sorry - I was probably not clear enough.
I wish to have a list of all the subs that go dark in a txt file. I guess that the subs you present on the website page are known in advance and the explicit names are stored in such a file.

**Comment by username-is-required** [comment]
you may already be aware of this (sorry if you are), but reddark pulls the list of subs that declared they’d participate from the [r/modcoord wiki page](https://reddit.com/r/modcoord/wiki/index). a json version can be accessed [here](https://reddit.com/r/modcoord/wiki/index.json), which could be parsed to make a list of just the individual subreddits.

in terms of filtering to **just those that went dark**, that might be a bit more tricky. it would require someone having stored some data on subreddits that changed their status to `private`/`restricted`, to then be able to filter the list down to those that blacked out. (iirc, about 96%-97% of the subs on the list blacked out at the peak of the 48hrs.)

while i’m not saying this data doesn’t exist (i don’t have the necessary information to suggest either way), it might be a challenge to find out who might have recorded it, and to gain access to it.

**Comment by abrahami** [comment]
Great - the json version is exactly the info I was looking for

thank you!
