### ISSUE TITLE
Suggestion: Manually specify public subreddits with satire rules

### ISSUE THREAD

**Issue by HonbraDev** [reddark-remix/reddark-remix#29]
With [r/pics going public but only allowing pictures of "John Oliver looking sexy"](https://reddit.simo.sh/r/pics/comments/14bai7s/henceforth_rpics_will_feature_only_images_of_john/), I think we need to have some sort of manual "override list" for these kinds of subs, as they're public yet still protesting.

<details>
<summary>Attachment</summary>
<img src="https://github.com/reddark-remix/reddark-remix/assets/54026315/6cd66c1c-b2a1-43dd-abe3-3c50b9f06eec" alt="John Oliver looking sexy" />
</details>

**Comment by rewbycraft** [comment]
A john-oliver list has been implemented. But I don't know of any other ways to easily distinguish other types of protest rules automatically.

If anyone is aware of more lists, do let me know with another issue.
