### ISSUE TITLE
idea: add John Oliver

### ISSUE THREAD

**Issue by FreyLuis** [reddark-remix/reddark-remix#31]
could you guys add john oliver as a status, for r/pics and r/gifs?

**Comment by username-is-required** [comment]
see also #29, though i prefer the idea of the status simply being ‘john oliver’

**Comment by username-is-required** [comment]
fyi i’ve started my own (currently completely manual, with script assistance) list of subs that have gone full John Oliver. while i can’t promise it’ll always be completelt accurate (given it relies on manual changes to keep it up to date), i’m hoping to create a new script (hopefully by the end of today) to provide me with some more help in maintaining it.

if any forks/instances would like to set their app to query it, feel completely free to do so. (i’ll be getting my fork to do that at some point)

link to file on github: https://github.com/username-is-required/reddark-subinfo/blob/main/john-oliver-subs.json

link to cdn that should always pull the latest version of the file: https://cdn.jsdelivr.net/gh/username-is-required/reddark-subinfo@main/john-oliver-subs.json
